#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mPower.Framework.Mvc.RazorHelpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 2 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
    using mPower.Framework.Services;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    public static class PaginatorHelper
    {

public static System.Web.WebPages.HelperResult Paginator(this HtmlHelper helper, PagingInfo info, string containerId, string refreshUrl)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 5 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
     
    if (info.TotalCount > 0)
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div class=\"pagination\">\r\n        <strong class=\"totals\">Showing ");



#line 9 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, info.IndexOfFirstItem);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " - ");



#line 9 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                     WebViewPage.WriteTo(@__razor_helper_writer, info.IndexOfLastItem);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " of ");



#line 9 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                                              WebViewPage.WriteTo(@__razor_helper_writer, info.TotalCount);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</strong>\r\n        <ul>\r\n");



#line 11 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
              int pageCount = info.TotalPagesCount;

#line default
#line hidden



#line 12 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
             if (info.CurrentPage > 1 && pageCount > 1)
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <li><a onclick=\"Grid.refresh(\'");



#line 14 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
   WebViewPage.WriteTo(@__razor_helper_writer, containerId);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\',\'");



#line 14 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                  WebViewPage.WriteTo(@__razor_helper_writer, refreshUrl);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\', ");



#line 14 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                                 WebViewPage.WriteTo(@__razor_helper_writer, info.CurrentPage - 1);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "); return false;\" href=\"#\">\r\n                    &#171;</a></li>\r\n");



#line 16 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
            }

#line default
#line hidden



#line 17 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
             if (pageCount > 1 && pageCount < 10)
            {
                for (int index = 0; index < pageCount; index++)
                {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <li>\r\n");



#line 22 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                     if (index == info.CurrentPage - 1)
                    {
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " <strong>");



#line 23 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, index + 1);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</strong>\r\n");



#line 24 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                    }
                    else
                    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        <a onclick=\"Grid.refresh(\'");



#line 27 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
       WebViewPage.WriteTo(@__razor_helper_writer, containerId);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\',\'");



#line 27 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                      WebViewPage.WriteTo(@__razor_helper_writer, refreshUrl);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\',");



#line 27 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                                    WebViewPage.WriteTo(@__razor_helper_writer, index + 1);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "); return false;\" href=\"#\">");



#line 27 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                                                                           WebViewPage.WriteTo(@__razor_helper_writer, index + 1);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\r\n");



#line 28 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                </li>\r\n");



#line 30 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                }
            }
            else if (pageCount >= 10)
            {
                int startIndex = Math.Min(info.CurrentPage > 4 ? info.CurrentPage - 4 : 1, pageCount - 8);
                if (startIndex > 1)
                {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <li>...</li>\r\n");



#line 38 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                }
                int i;
                for (i = startIndex; (i < startIndex + 9) && i <= pageCount; i++)
                {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <li>\r\n");



#line 43 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                     if (i == info.CurrentPage)
                    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        <strong>");



#line 45 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, i);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</strong>\r\n");



#line 46 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                    }
                    else
                    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        <a onclick=\"Grid.refresh(\'");



#line 49 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
       WebViewPage.WriteTo(@__razor_helper_writer, containerId);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\',\'");



#line 49 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                      WebViewPage.WriteTo(@__razor_helper_writer, refreshUrl);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\',");



#line 49 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                                   WebViewPage.WriteTo(@__razor_helper_writer, i);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "); return false;\" href=\"#\">");



#line 49 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                                                                WebViewPage.WriteTo(@__razor_helper_writer, i);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\r\n");



#line 50 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                </li>\r\n");



#line 52 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                }
                if (i < pageCount)
                {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <li>...</li>\r\n");



#line 56 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                }
            }

#line default
#line hidden



#line 58 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
             if (pageCount > info.CurrentPage + 1 && pageCount > 1)
            { 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <li><a onclick=\"Grid.refresh(\'");



#line 60 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
   WebViewPage.WriteTo(@__razor_helper_writer, containerId);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\',\'");



#line 60 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                  WebViewPage.WriteTo(@__razor_helper_writer, refreshUrl);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\',");



#line 60 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
                                WebViewPage.WriteTo(@__razor_helper_writer, info.CurrentPage + 1);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "); return false;\" href=\"#\">\r\n                    &#187;</a></li>\r\n");



#line 62 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
            }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </ul>\r\n    </div>\r\n");



#line 65 "..\..\Mvc\RazorHelpers\PaginatorHelper.cshtml"
    }

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
