#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Default.Models.Helpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Models\Helpers\EntryListHelper.cshtml"
    using Default.ViewModel;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Models\Helpers\EntryListHelper.cshtml"
    using Default.ViewModel.Areas.Shared;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Models\Helpers\EntryListHelper.cshtml"
    using mPower.Framework.Mvc.RazorHelpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    public static class EntryListHelper
    {

public static System.Web.WebPages.HelperResult GenerateEntryRows(IEnumerable<Entry> entries, IEnumerable<GroupedSelectListItem> accounts, int maxDescriptionLength = 43, bool isFake = false)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 8 "..\..\Models\Helpers\EntryListHelper.cshtml"
 
    foreach (var entry in entries)
    {
        var descriptionString = entry.Payee.Ellipsize(maxDescriptionLength);
        

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <tr id=\"");



#line 13 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, String.Concat("row_", entry.TransactionId));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n            <td>\r\n                <div class=\"table-cell-top-left\">");



#line 15 "..\..\Models\Helpers\EntryListHelper.cshtml"
      WebViewPage.WriteTo(@__razor_helper_writer, entry.AccountName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</div>\r\n                <input name=\"\" type=\"checkbox\" value=\"\" />\r\n            <" +
"/td>\r\n            <td class=\"_entrySelector trans_date\">");



#line 18 "..\..\Models\Helpers\EntryListHelper.cshtml"
       WebViewPage.WriteTo(@__razor_helper_writer, entry.BookedDate.ToShortDateString());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</td>\r\n            <td class=\"_entrySelector\" nowrap=\"nowrap\">");



#line 19 "..\..\Models\Helpers\EntryListHelper.cshtml"
            WebViewPage.WriteTo(@__razor_helper_writer, descriptionString);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</td>\r\n            <td>\r\n                <div id=\"menu\">\r\n                    ");



#line 22 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, isFake 
                    ? EntryCatergorizationFakeSelectList(accounts, entry.OffsetAccountId, entry.TransactionId, entry.AccountId) 
                    : EntryCatergorizationSelectList(accounts, entry.OffsetAccountId, entry.TransactionId, entry.AccountId));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n                </div>\r\n            </td>\r\n            <td class=\"");



#line 27 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, entry.FormattedAmountInDollars.StartsWith("-") ? "" : "positive");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " rt _entrySelector\">");



#line 27 "..\..\Models\Helpers\EntryListHelper.cshtml"
                                                                   WebViewPage.WriteTo(@__razor_helper_writer, entry.FormattedAmountInDollars);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</td>\r\n        </tr>      \r\n");



#line 29 "..\..\Models\Helpers\EntryListHelper.cshtml"
    }       

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult EntryCatergorizationSelectList(IEnumerable<GroupedSelectListItem> accounts, string selectedAccountId, string transactionId, string baseAccountId, string id = "")
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 34 "..\..\Models\Helpers\EntryListHelper.cshtml"
     

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <select ");



#line 35 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, !String.IsNullOrEmpty(id) ? String.Format("id={0}", id) : String.Empty);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " name=\"");



#line 35 "..\..\Models\Helpers\EntryListHelper.cshtml"
                                                 WebViewPage.WriteTo(@__razor_helper_writer, String.Concat(transactionId, '_', selectedAccountId));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" class=\"_entryCategory combobox\">\r\n\t\t<option value=\"add new\">Add New | |</option" +
">\r\n");



#line 37 "..\..\Models\Helpers\EntryListHelper.cshtml"
  		 
            var categories = new List<string> { 
				"Income",
				"Expense",
				"Transfer/Payment",
				"Other Accounts"
			};

            var groupedAccounts = categories.GroupJoin(accounts, x => x, y => y.Group, (_, y) => y);            

            foreach (var group in groupedAccounts)
            {
                
                var currentList = group.OrderBy(x =>
                {
                    string[] splitText = x.Text.Split('|');

                    return splitText.Last();
                });

                foreach (var listItem in currentList)
                {
                    var selectedText = listItem.Value == selectedAccountId ? "selected=selected" : String.Empty;

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\t\t\t\t\t<option value=\"");



#line 60 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, listItem.Value);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" ");



#line 60 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, selectedText);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">");



#line 60 "..\..\Models\Helpers\EntryListHelper.cshtml"
        WebViewPage.WriteTo(@__razor_helper_writer, listItem.Text);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " | ");



#line 60 "..\..\Models\Helpers\EntryListHelper.cshtml"
                         WebViewPage.WriteTo(@__razor_helper_writer, listItem.Group);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</option>\r\n");



#line 61 "..\..\Models\Helpers\EntryListHelper.cshtml"
                }
            }
		 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </select>\r\n");



#line 65 "..\..\Models\Helpers\EntryListHelper.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult EntryCatergorizationFakeSelectList(IEnumerable<GroupedSelectListItem> accounts, string selectedAccountId, string transactionId, string baseAccountId, string cssClass = "")
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 68 "..\..\Models\Helpers\EntryListHelper.cshtml"
     

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <select name=\"");



#line 69 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, String.Concat(transactionId, '_', selectedAccountId));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" class=\"_entryCategory combobox ");



#line 69 "..\..\Models\Helpers\EntryListHelper.cshtml"
                                                             WebViewPage.WriteTo(@__razor_helper_writer, cssClass);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n");



#line 70 "..\..\Models\Helpers\EntryListHelper.cshtml"
              var item = accounts.First(x => x.Value == selectedAccountId);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <option value=\"");



#line 71 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, item.Value);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" selected=\"selected\">");



#line 71 "..\..\Models\Helpers\EntryListHelper.cshtml"
                 WebViewPage.WriteTo(@__razor_helper_writer, item.Text);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " | ");



#line 71 "..\..\Models\Helpers\EntryListHelper.cshtml"
                              WebViewPage.WriteTo(@__razor_helper_writer, item.Group);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</option>            \r\n    </select>\r\n");



#line 73 "..\..\Models\Helpers\EntryListHelper.cshtml"


#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult TransactionCatergorizationSelectList(IEnumerable<GroupedSelectListItem> categories, string selectName, string selectClass, string selectedAccountId = null)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 78 "..\..\Models\Helpers\EntryListHelper.cshtml"
     

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <select name=\"");



#line 79 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, selectName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" class=\"");



#line 79 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, selectClass);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n        <option value=\" \">Select Account ...| |</option>\r\n        \r\n        ");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n                \r\n");



#line 84 "..\..\Models\Helpers\EntryListHelper.cshtml"
         foreach (var cat in categories.Where(x => x.Group == "Income"))
        {
            var selectedText = cat.Value == selectedAccountId ? "selected=selected" : String.Empty;

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <option value=\"");



#line 87 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, cat.Value);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" ");



#line 87 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, selectedText);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">");



#line 87 "..\..\Models\Helpers\EntryListHelper.cshtml"
          WebViewPage.WriteTo(@__razor_helper_writer, cat.Text);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " | ");



#line 87 "..\..\Models\Helpers\EntryListHelper.cshtml"
                      WebViewPage.WriteTo(@__razor_helper_writer, cat.Group);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</option>\r\n");



#line 88 "..\..\Models\Helpers\EntryListHelper.cshtml"
        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 90 "..\..\Models\Helpers\EntryListHelper.cshtml"
         foreach (var cat in categories.Where(x => x.Group == "Expense"))
        {
            var selectedText = cat.Value == selectedAccountId ? "selected=selected" : String.Empty;

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <option value=\"");



#line 93 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, cat.Value);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" ");



#line 93 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, selectedText);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">");



#line 93 "..\..\Models\Helpers\EntryListHelper.cshtml"
          WebViewPage.WriteTo(@__razor_helper_writer, cat.Text);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " | ");



#line 93 "..\..\Models\Helpers\EntryListHelper.cshtml"
                      WebViewPage.WriteTo(@__razor_helper_writer, cat.Group);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</option>\r\n");



#line 94 "..\..\Models\Helpers\EntryListHelper.cshtml"
        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                \r\n");



#line 96 "..\..\Models\Helpers\EntryListHelper.cshtml"
         foreach (var cat in categories.Where(x => x.Group == "Transfer/Payment"))
        {
            var selectedText = cat.Value == selectedAccountId ? "selected=selected" : String.Empty;

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <option value=\"");



#line 99 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, cat.Value);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" ");



#line 99 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, selectedText);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">");



#line 99 "..\..\Models\Helpers\EntryListHelper.cshtml"
          WebViewPage.WriteTo(@__razor_helper_writer, cat.Text);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " | ");



#line 99 "..\..\Models\Helpers\EntryListHelper.cshtml"
                      WebViewPage.WriteTo(@__razor_helper_writer, cat.Group);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</option>\r\n");



#line 100 "..\..\Models\Helpers\EntryListHelper.cshtml"
        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 102 "..\..\Models\Helpers\EntryListHelper.cshtml"
         foreach (var cat in categories.Where(x => x.Group == "Other Accounts"))
        {
            var selectedText = cat.Value == selectedAccountId ? "selected=selected" : String.Empty;

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <option value=\"");



#line 105 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, cat.Value);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" ");



#line 105 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, selectedText);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">");



#line 105 "..\..\Models\Helpers\EntryListHelper.cshtml"
          WebViewPage.WriteTo(@__razor_helper_writer, cat.Text);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " | ");



#line 105 "..\..\Models\Helpers\EntryListHelper.cshtml"
                      WebViewPage.WriteTo(@__razor_helper_writer, cat.Group);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</option>\r\n");



#line 106 "..\..\Models\Helpers\EntryListHelper.cshtml"
        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        \r\n    </select>\r\n");



#line 109 "..\..\Models\Helpers\EntryListHelper.cshtml"
        

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult DisplayDropDown(IEnumerable<Category> categories, string selectedAccountName, string selectedAccountId, string transactionId, string baseAccountId)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 113 "..\..\Models\Helpers\EntryListHelper.cshtml"
     

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <ul class=\"menu\" id=\"menu\">\r\n        <li><a class=\"menulink\">");



#line 115 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, selectedAccountName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\r\n");



#line 116 "..\..\Models\Helpers\EntryListHelper.cshtml"
             if (!selectedAccountName.Equals("Split"))
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <ul>\r\n");



#line 119 "..\..\Models\Helpers\EntryListHelper.cshtml"
                     foreach (var cat in categories.Where(x => String.IsNullOrEmpty(x.ParentAccountId) && x.AccountId != baseAccountId))
                    {                   

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        <li><a id=\"");



#line 121 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, String.Concat(transactionId, '_', selectedAccountId, '_', cat.AccountId));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" class=\"_entryCategory\" href=\"#\" name=\"");



#line 121 "..\..\Models\Helpers\EntryListHelper.cshtml"
                                                                                                         WebViewPage.WriteTo(@__razor_helper_writer, transactionId);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 121 "..\..\Models\Helpers\EntryListHelper.cshtml"
                                                                                                                         WebViewPage.WriteTo(@__razor_helper_writer, cat.AccountName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " <span class=\"dropdown-accountlabel\">");



#line 121 "..\..\Models\Helpers\EntryListHelper.cshtml"
                                                                                                                                                                              WebViewPage.WriteTo(@__razor_helper_writer, cat.AccountLabel);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</span></a>\r\n                            ");



#line 122 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Hierarchy(categories, cat.AccountId, transactionId, selectedAccountId, "sub", baseAccountId));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n                        </li>\r\n");



#line 124 "..\..\Models\Helpers\EntryListHelper.cshtml"
                    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    <li><a id=\"\" class=\"sub\" >Multiple Accounts...</a> </li>\r\n   " +
"             </ul>\r\n");



#line 127 "..\..\Models\Helpers\EntryListHelper.cshtml"
            }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </li>\r\n    </ul>\r\n");



#line 130 "..\..\Models\Helpers\EntryListHelper.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Hierarchy(IEnumerable<Category> categories, string accountId, string transactionId, string offsetAccountId, string subClass, string baseAccountId)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 134 "..\..\Models\Helpers\EntryListHelper.cshtml"
                     
    if (categories.Count(x => x.ParentAccountId == accountId) > 0)
    {

        foreach (var sub in categories.Where(x => x.ParentAccountId == accountId && x.AccountId != baseAccountId))
        {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <li><a id=\"");



#line 140 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, String.Concat(transactionId, '_', offsetAccountId, '_', sub.AccountId));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" href=\"#\" class=\"");



#line 140 "..\..\Models\Helpers\EntryListHelper.cshtml"
                                                                         WebViewPage.WriteTo(@__razor_helper_writer, subClass);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " _entryCategory\">");



#line 140 "..\..\Models\Helpers\EntryListHelper.cshtml"
                                                                                                   WebViewPage.WriteTo(@__razor_helper_writer, sub.AccountName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\r\n                    ");



#line 141 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Hierarchy(categories, sub.AccountId, transactionId, offsetAccountId, subClass + "sub", baseAccountId));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n                </li>           \r\n");



#line 143 "..\..\Models\Helpers\EntryListHelper.cshtml"
        }
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult AccountDropDown(IEnumerable<Category> categories, string selectedAccountName = " ", string selectedAccountId = " ")
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 149 "..\..\Models\Helpers\EntryListHelper.cshtml"
     

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <ul class=\"menu\" id=\"menu\">\r\n        <li>\r\n            <a href=\"#\" class=\"men" +
"ulink selectedCategory\">");



#line 152 "..\..\Models\Helpers\EntryListHelper.cshtml"
               WebViewPage.WriteTo(@__razor_helper_writer, selectedAccountName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\r\n            <ul>\r\n");



#line 154 "..\..\Models\Helpers\EntryListHelper.cshtml"
                 foreach (var cat in categories.Where(x => String.IsNullOrEmpty(x.ParentAccountId)))
                {                   

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    <li>\r\n                        <a id=\"");



#line 157 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, String.Concat(cat.AccountId, "_", cat.AccountName));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" class=\"_transactionAccount\" href=\"#\">\r\n                            ");



#line 158 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, cat.AccountName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " \r\n                            <span class=\"dropdown-accountlabel\">");



#line 159 "..\..\Models\Helpers\EntryListHelper.cshtml"
                     WebViewPage.WriteTo(@__razor_helper_writer, cat.AccountLabel);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</span>\r\n                        </a>\r\n                        ");



#line 161 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, AccountDropDownHierarchy(categories, cat.AccountId, selectedAccountId, "sub"));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n                    </li>\r\n");



#line 163 "..\..\Models\Helpers\EntryListHelper.cshtml"
                }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "               \r\n            </ul>\r\n            \r\n        </li>\r\n    </ul>\r\n");



#line 169 "..\..\Models\Helpers\EntryListHelper.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult AccountDropDownHierarchy(IEnumerable<Category> categories, string accountId, string offsetAccountId, string subClass)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 173 "..\..\Models\Helpers\EntryListHelper.cshtml"
                     
    if (categories.Count(x => x.ParentAccountId == accountId) > 0)
    {

        foreach (var sub in categories.Where(x => x.ParentAccountId == accountId))
        {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <li><a id=\"");



#line 179 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, String.Concat(sub.AccountId, "_", sub.AccountName));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" href=\"#\" class=\"");



#line 179 "..\..\Models\Helpers\EntryListHelper.cshtml"
                                                     WebViewPage.WriteTo(@__razor_helper_writer, subClass);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " _transactionAccount\">");



#line 179 "..\..\Models\Helpers\EntryListHelper.cshtml"
                                                                                    WebViewPage.WriteTo(@__razor_helper_writer, sub.AccountName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\r\n                    ");



#line 180 "..\..\Models\Helpers\EntryListHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, AccountDropDownHierarchy(categories, sub.AccountId, offsetAccountId, subClass + "sub"));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n                </li>           \r\n");



#line 182 "..\..\Models\Helpers\EntryListHelper.cshtml"
        }
    }

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
