#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Default.Models.Helpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
    using mPower.Aggregation.Contract.Data;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
    using mPower.Aggregation.Contract.Documents;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    public static class GettingStartedHelper
    {

public static System.Web.WebPages.HelperResult AuthenticateToInstitutionHtml_Intuit(IList<KeyDocument> docs)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 7 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
 
    if (docs == null)
    {
        return;
    }

    for (var i = 0; i < docs.Count(); i++)
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <label>");



#line 15 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, docs[i].Description);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</label>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <input type=\"hidden\" name=\"keys[");



#line 16 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, i);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "].Name\" value=\"");



#line 16 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
              WebViewPage.WriteTo(@__razor_helper_writer, docs[i].Name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" />\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <input type=\"hidden\" name=\"keys[");



#line 17 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, i);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "].InstitutionKeyId\" value=\"");



#line 17 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
                          WebViewPage.WriteTo(@__razor_helper_writer, docs[i].InstitutionKeyId);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" />\r\n");



#line 18 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
        
        var displayType = docs[i].Name.ToLower().Contains("pass") || docs[i].Description.ToLower().Contains("pass") ? "Password" : "Text";
           

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <input type=\"");



#line 21 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, displayType);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" name=\"keys[");



#line 21 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
   WebViewPage.WriteTo(@__razor_helper_writer, i);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "].Value\" value=\"");



#line 21 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
                     WebViewPage.WriteTo(@__razor_helper_writer, docs[i].Value);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" />\r\n");



#line 22 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
    }
    

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <input type=\"submit\" id=\"submit\" value=\"Submit\" class=\"main-button-medium fRi" +
"ght\" />\t\r\n");



#line 25 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
       


#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult MfaQuestionsHtml(AggregationQuestion[] questions)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 30 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
 
    for (var i = 0; i < questions.Length; i++)
    {
        var question = questions[i];
        foreach (var item in question.Items)
        {
            if (item is Guid)
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <img src=\'/Aggregation/GetQuestionImage?imageId=");



#line 38 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
                     WebViewPage.WriteTo(@__razor_helper_writer, item);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\' alt=\"img\" style=\"float: left;\" />\r\n");



#line 39 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
            }
            else
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <label>");



#line 42 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, item.ToString());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</label>\r\n");



#line 43 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
            }
        }
        if (question.Choices != null && question.Choices.Any())
        {
            // default value

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <input type=\"radio\" name=\"[");



#line 48 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, i);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "]\" value=\"\" checked=\"checked\" style=\"display: none;\" />\r\n");



#line 49 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
    
            foreach (var value in question.Choices)
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <input type=\"radio\" name=\"[");



#line 52 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, i);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "]\" id=\"");



#line 52 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
         WebViewPage.WriteTo(@__razor_helper_writer, value);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" value=\"");



#line 52 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
                        WebViewPage.WriteTo(@__razor_helper_writer, value);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" />\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <label for=\"");



#line 53 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, value);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" style=\"display: inline;\">");



#line 53 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
                  WebViewPage.WriteTo(@__razor_helper_writer, value);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</label>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <br/>\r\n");



#line 55 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
            }
        }
        else
        {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <input type=\"text\" name=\"[");



#line 59 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, i);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "]\" class=\"bank-connect-form-label\" />\r\n");



#line 60 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <br/>\r\n");



#line 62 "..\..\Models\Helpers\GettingStartedHelper.cshtml"
    }


#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div class=\"clear\"></div>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div class=\"mfa-input-container tb-spaced\">\r\n        <input id=\"submit\" type=" +
"\"submit\" value=\"Submit\" class=\"main-button-large fRight\" />\r\n    </div>\r\n");



#line 68 "..\..\Models\Helpers\GettingStartedHelper.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
