#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Default.Models.Helpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 1 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"
    using mPower.Domain.Accounting;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    public static class SpendingCategoryHelper
    {

public static System.Web.WebPages.HelperResult GenerateCategoriesList(string name, List<RootExpenseAccount> spendingCategories, string selectedValue)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 6 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"
 
    var id = new Regex("[\\[\\]\\.]").Replace(name, "_");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <select id=\"");



#line 8 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" name=\"");



#line 8 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n        <option ");



#line 9 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, GetSelectedAttr(selectedValue, ""));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " value=\"\">-- Select --</option>\r\n");



#line 10 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"
         if (spendingCategories != null)
        {
            foreach (var acc in spendingCategories)
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <option value=\"");



#line 14 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, acc.Name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" ");



#line 14 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, GetSelectedAttr(selectedValue, @acc.Name));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " data-id=\"");



#line 14 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"
                                                   WebViewPage.WriteTo(@__razor_helper_writer, acc.Name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 14 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"
                                                              WebViewPage.WriteTo(@__razor_helper_writer, acc.Name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</option>    \r\n");



#line 15 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"
                foreach (var subAcc in acc.SubAccounts)
                {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    <option value=\"");



#line 17 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, subAcc.Name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" ");



#line 17 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"
      WebViewPage.WriteTo(@__razor_helper_writer, GetSelectedAttr(selectedValue, @subAcc.Name));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " data-id=\"");



#line 17 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"
                                                             WebViewPage.WriteTo(@__razor_helper_writer, subAcc.Name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-parent-id=\"");



#line 17 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"
                                                                                           WebViewPage.WriteTo(@__razor_helper_writer, acc.Name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 17 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"
                                                                                                      WebViewPage.WriteTo(@__razor_helper_writer, subAcc.Name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</option>\r\n");



#line 18 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"
                }
            }
        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </select>\r\n");



#line 22 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"

#line default
#line hidden

});

}


        #line 25 "..\..\Models\Helpers\SpendingCategoryHelper.cshtml"

    static string GetSelectedAttr(string selectedValue, string value)
    {
        return (selectedValue ?? string.Empty) == value ? "selected='selected'" : "";
    }


        #line default
        #line hidden

    }
}
#pragma warning restore 1591
