#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Default.Models.Helpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    public static class TopNavigation
    {

public static System.Web.WebPages.HelperResult Build(bool affiliateAdmin, bool globalAdmin, bool pfmEnabled, bool bfmEnabled, bool creditAppEnabled)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 3 "..\..\Models\Helpers\TopNavigation.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <select id=\"navigationDropDown\">\n        \n");



#line 6 "..\..\Models\Helpers\TopNavigation.cshtml"
         if(pfmEnabled)
        {
            
#line default
#line hidden


#line 8 "..\..\Models\Helpers\TopNavigation.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Option("Personal Finances", "/Finance"));

#line default
#line hidden


#line 8 "..\..\Models\Helpers\TopNavigation.cshtml"
                                                    
        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        \n");



#line 11 "..\..\Models\Helpers\TopNavigation.cshtml"
         if(creditAppEnabled)
        {
            
#line default
#line hidden


#line 13 "..\..\Models\Helpers\TopNavigation.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Option("Credit Identity", "/Credit"));

#line default
#line hidden


#line 13 "..\..\Models\Helpers\TopNavigation.cshtml"
                                                 
        }

#line default
#line hidden



#line 15 "..\..\Models\Helpers\TopNavigation.cshtml"
         if(bfmEnabled)
        {
             
#line default
#line hidden


#line 17 "..\..\Models\Helpers\TopNavigation.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Option("Business Finances", "/Business"));

#line default
#line hidden


#line 17 "..\..\Models\Helpers\TopNavigation.cshtml"
                                                      
        }

#line default
#line hidden



#line 19 "..\..\Models\Helpers\TopNavigation.cshtml"
         if (affiliateAdmin)
        {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " ");



#line 21 "..\..\Models\Helpers\TopNavigation.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Option("Affiliate Admin", "/Administration/Affiliate", "/Administration/Analytics", "/Administration/Marketing"));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 22 "..\..\Models\Helpers\TopNavigation.cshtml"
        }

#line default
#line hidden



#line 23 "..\..\Models\Helpers\TopNavigation.cshtml"
         if (globalAdmin)
        {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " ");



#line 25 "..\..\Models\Helpers\TopNavigation.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Option("Global Admin", "/Administration/Global"));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 26 "..\..\Models\Helpers\TopNavigation.cshtml"
        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </select>\n");



#line 28 "..\..\Models\Helpers\TopNavigation.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Option(string title, params string [] values)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 30 "..\..\Models\Helpers\TopNavigation.cshtml"
 
    var selected = false;
    foreach (var v in values)
    {
        selected |= HttpContext.Current.Request.Url.LocalPath.ToLower().StartsWith(v.ToLower());
    }
    

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <option ");



#line 37 "..\..\Models\Helpers\TopNavigation.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, selected ? "selected='selected'" : "");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " value=\"");



#line 37 "..\..\Models\Helpers\TopNavigation.cshtml"
                 WebViewPage.WriteTo(@__razor_helper_writer, values.First());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 37 "..\..\Models\Helpers\TopNavigation.cshtml"
                                  WebViewPage.WriteTo(@__razor_helper_writer, title);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</option>\n");



#line 38 "..\..\Models\Helpers\TopNavigation.cshtml"

#line default
#line hidden

});

}


        #line 40 "..\..\Models\Helpers\TopNavigation.cshtml"

    public static bool IsMoreThanOneAreaAllowed(params bool [] areaIsEnabled)
    {
        return areaIsEnabled.Count(x => x) > 1;
    }

        #line default
        #line hidden

    }
}
#pragma warning restore 1591
