#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mPower.Web.Admin.Helpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 3 "..\..\Helpers\PaginatorHelper.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Helpers\PaginatorHelper.cshtml"
    using mPower.Framework.Services;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    public static class PaginatorHelper
    {

public static System.Web.WebPages.HelperResult Paginator(this HtmlHelper helper, mPower.Web.Admin.Models.LogsModel info, string className) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 5 "..\..\Helpers\PaginatorHelper.cshtml"
                                                                                                     
    if (info.PaginInfo.TotalPagesCount > 1)
    {


#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <div class=\"");



#line 9 "..\..\Helpers\PaginatorHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, className);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n            <ul>\r\n");



#line 11 "..\..\Helpers\PaginatorHelper.cshtml"
                   int pageCount = info.PaginInfo.TotalPagesCount; 

#line default
#line hidden



#line 12 "..\..\Helpers\PaginatorHelper.cshtml"
                 if (info.PaginInfo.HasPreviousPage)
                {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    <li>\r\n                        <a href=\"");



#line 15 "..\..\Helpers\PaginatorHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, string.Format("/logs/Index?searchKey={0}&date={1}&sort={2}&level={3}&pageNr={4}&pageSize={5}",
                                                             info.SearchKey,
                                                             info.DateOptions.First(x => x.Selected).Value,
                                                             info.SortOptions.First(x => x.Selected).Value,
                                                             info.LevelOptions.First(x => x.Selected).Value,
                                                             info.PaginInfo.CurrentPage - 1,
                                                             info.PaginInfo.ItemsPerPage));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n                            &#171;\r\n                        </a>\r\n           " +
"         </li>\r\n");



#line 25 "..\..\Helpers\PaginatorHelper.cshtml"
                }

#line default
#line hidden



#line 26 "..\..\Helpers\PaginatorHelper.cshtml"
                  
                    int startIndex = Math.Min(info.PaginInfo.CurrentPage > 4 ? info.PaginInfo.CurrentPage - 4 : 1, pageCount - 8);
                    startIndex = startIndex >= 1 ? startIndex : 1;
                    if (startIndex > 1)
                    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        <li>...</li>\r\n");



#line 32 "..\..\Helpers\PaginatorHelper.cshtml"
                    }
                    int i;
                    for (i = startIndex; (i < startIndex + 9) && i <= pageCount; i++)
                    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        <li>\r\n");



#line 37 "..\..\Helpers\PaginatorHelper.cshtml"
                             if (i == info.PaginInfo.CurrentPage)
                            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                                <strong>");



#line 39 "..\..\Helpers\PaginatorHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, i);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</strong>\r\n");



#line 40 "..\..\Helpers\PaginatorHelper.cshtml"
                            }
                            else
                            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                                <a href=\"");



#line 43 "..\..\Helpers\PaginatorHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, string.Format("/logs/Index?searchKey={0}&date={1}&sort={2}&level={3}&pageNr={4}&pageSize={5}",
                                                                     info.SearchKey,
                                                                     info.DateOptions.First(x => x.Selected).Value,
                                                                     info.SortOptions.First(x => x.Selected).Value,
                                                                     info.LevelOptions.First(x => x.Selected).Value,
                                                                     i,
                                                                     info.PaginInfo.ItemsPerPage));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n                                    ");



#line 50 "..\..\Helpers\PaginatorHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, i);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n                                </a>\r\n");



#line 52 "..\..\Helpers\PaginatorHelper.cshtml"
                            }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        </li>\r\n");



#line 54 "..\..\Helpers\PaginatorHelper.cshtml"
                    }
                    if (i < pageCount)
                    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        <li>...</li>\r\n");



#line 58 "..\..\Helpers\PaginatorHelper.cshtml"
                    }
                

#line default
#line hidden



#line 60 "..\..\Helpers\PaginatorHelper.cshtml"
                 if (info.PaginInfo.HasNextPage)
                {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    <li>\r\n                        <a href=\"");



#line 63 "..\..\Helpers\PaginatorHelper.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, string.Format("/logs/Index?searchKey={0}&date={1}&sort={2}&level={3}&pageNr={4}&pageSize={5}",
                                                             info.SearchKey,
                                                             info.DateOptions.First(x => x.Selected).Value,
                                                             info.SortOptions.First(x => x.Selected).Value,
                                                             info.LevelOptions.First(x => x.Selected).Value,
                                                             info.PaginInfo.CurrentPage + 1,
                                                             info.PaginInfo.ItemsPerPage));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n                            &#187;\r\n                        </a>\r\n           " +
"         </li>\r\n");



#line 73 "..\..\Helpers\PaginatorHelper.cshtml"
                }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            </ul>\r\n        </div>\r\n");



#line 76 "..\..\Helpers\PaginatorHelper.cshtml"
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Paging(this HtmlHelper helper, PagingInfo info) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 79 "..\..\Helpers\PaginatorHelper.cshtml"
                                                                 
            if (info.TotalPagesCount > 1)
            {


#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <div id=\"paging\" class=\"paginator\">\r\n                    <ul>\r\n");



#line 85 "..\..\Helpers\PaginatorHelper.cshtml"
                           int pageCount = info.TotalPagesCount; 

#line default
#line hidden



#line 86 "..\..\Helpers\PaginatorHelper.cshtml"
                         if (info.HasPreviousPage)
                        {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            <li>\r\n                                <a href=\"#\" dat" +
"a-page=\"");



#line 89 "..\..\Helpers\PaginatorHelper.cshtml"
             WebViewPage.WriteTo(@__razor_helper_writer, info.CurrentPage -1);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n                                    &#171;\r\n                                <" +
"/a>\r\n                            </li>\r\n");



#line 93 "..\..\Helpers\PaginatorHelper.cshtml"
                        }

#line default
#line hidden



#line 94 "..\..\Helpers\PaginatorHelper.cshtml"
                          
                            int startIndex = Math.Min(info.CurrentPage > 4 ? info.CurrentPage - 4 : 1, pageCount - 8);
                            startIndex = startIndex >= 1 ? startIndex : 1;
                            if (startIndex > 1)
                            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                                <li>...</li>\r\n");



#line 100 "..\..\Helpers\PaginatorHelper.cshtml"
                            }
                            int i;
                            for (i = startIndex; (i < startIndex + 9) && i <= pageCount; i++)
                            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                                <li>\r\n");



#line 105 "..\..\Helpers\PaginatorHelper.cshtml"
                                     if (i == info.CurrentPage)
                                    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                                        <strong>");



#line 107 "..\..\Helpers\PaginatorHelper.cshtml"
     WebViewPage.WriteTo(@__razor_helper_writer, i);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</strong>\r\n");



#line 108 "..\..\Helpers\PaginatorHelper.cshtml"
                                    }
                                    else
                                    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                                        <a href=\"#\" data-page=\"");



#line 111 "..\..\Helpers\PaginatorHelper.cshtml"
                     WebViewPage.WriteTo(@__razor_helper_writer, i);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n                                            ");



#line 112 "..\..\Helpers\PaginatorHelper.cshtml"
 WebViewPage.WriteTo(@__razor_helper_writer, i);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n                                        </a>\r\n");



#line 114 "..\..\Helpers\PaginatorHelper.cshtml"
                                    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                                </li>\r\n");



#line 116 "..\..\Helpers\PaginatorHelper.cshtml"
                            }
                            if (i < pageCount)
                            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                                <li>...</li>\r\n");



#line 120 "..\..\Helpers\PaginatorHelper.cshtml"
                            }
                        

#line default
#line hidden



#line 122 "..\..\Helpers\PaginatorHelper.cshtml"
                         if (info.HasNextPage)
                        {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            <li>\r\n                                <a href=\"#\" dat" +
"a-page=\"");



#line 125 "..\..\Helpers\PaginatorHelper.cshtml"
             WebViewPage.WriteTo(@__razor_helper_writer, info.CurrentPage  + 1);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n                                    &#187;\r\n                                <" +
"/a>\r\n                            </li>\r\n");



#line 129 "..\..\Helpers\PaginatorHelper.cshtml"
                        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    </ul>\r\n                </div>\r\n");



#line 132 "..\..\Helpers\PaginatorHelper.cshtml"
            }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, @"            <script>
                $(""#paging li a"").click(function () {
                    var pageNumberInput = $(""input[name*='PagingInfo.CurrentPage']"");
                    pageNumberInput.val($(this).data(""page""));
                    pageNumberInput.parents(""form"").submit();
                })
            </script>
");



#line 140 "..\..\Helpers\PaginatorHelper.cshtml"
        
#line default
#line hidden

});

        }


    }
}
#pragma warning restore 1591
